services:
  - type: web
    name: rick-morty-frontend
    env: nextjs
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false # Configurar en el Dashboard (ej. https://rick-morty-backend.onrender.com)
